### ISSUE TITLE
CI is not working because Cypress could not verify that the server is running

### ISSUE THREAD

**Issue by rblancou** [bahmutov/cypress-workflows#27]
Hello 😺 

I'm trying to use your `cypress-workflows` Github Action in a simple way but when the workflow is launched there is an error for each container related to not server found.

Here is my workflow code:

```
name: CI - E2E Tests
on: [push]
jobs:
  e2e-tests:
    name: Launch E2E tests in parallel
    # https://github.com/bahmutov/cypress-workflows
    uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v2
    with:
      nE2E: 3
```

Here is the error on CI job:

![image](https://github.com/bahmutov/cypress-workflows/assets/6724744/ef5d4207-1010-41fb-8d1d-7661aff6cf2d)

*How can I solve it?*
