### ISSUE TITLE
Grab screenshots, videos, and results folder in a single test artifact

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-workflows#7]
So that relative paths work together

```yml
# capture screenshots, videos, Mochawesome reports
# https://github.com/actions/upload-artifact
- uses: actions/upload-artifact@v3
  if: ${{ always() }}
  with:
    name: cypress-results
    path: |
      cypress/screenshots
      cypress/videos
      cypress/results
    if-no-files-found: ignore
```
